spring:
  application:
    name: notification-service

  profiles:
    active: elk

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}
    connection-timeout: 5s
    requested-heartbeat: 30s

    listener:
      simple:
        prefetch: 10
        concurrency: 3
        max-concurrency: 10
        acknowledge-mode: auto
        default-requeue-rejected: false
        retry:
          enabled: true
          initial-interval: 2s
          max-attempts: 3
          multiplier: 2.0
          max-interval: 10s

server:
  port: 8082

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0    # в демо берём 100%, в production меньше (0.1, 0.01)
    propagation:
      type: w3c           # W3C Trace Context, traceparent: содержит Trace ID, Span ID и флаги трассировки
  otlp:
    tracing:
      endpoint: http://jaeger:4318/v1/traces
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - info
          - prometheus
          - loggers