spring:
  application:
    name: OrderHubProjectApplication

  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:order_hub_db}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
        order_updates: true
        order_insets: true
        generate_statistics: true

  liquibase:
    enabled: true
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    change-log: classpath:/db/changelog/changelog_master.yaml

server:
  port: 8080

management:
  info:
    env:
      enabled: true

  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
          - loggers

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

info:
  app:
    name: "OrderHub"
    version: "0.0.1"
    description: "Learning..."