spring:
  application:
    name: OrderHubProjectApplication

  datasource:
    url: jdbc:postgresql://localhost:5435/order_hub_db
    username: postgres_user
    password: postgres_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true
    user: postgres_user
    password: postgres_password
    change-log: classpath:/db/changelog/changelog_master.yaml

server:
  port: 8080

logging:
  level:
    org.hibernate.sql: DEBUG
