spring:
  application:
    name: order-service

  profiles:
    active: elk

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:order_hub_db}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
        order_updates: true
        order_insets: true
        generate_statistics: true

  liquibase:
    enabled: true
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    change-log: classpath:/changelog/changelog_master.yaml

  task:
    scheduling:
      pool:
        size: 5
      thread-name-prefix: "scheduled-"
      shutdown:
        await-termination: true

server:
  port: 8080

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://jaeger:4318/v1/traces


  prometheus:
    metrics:
      export:
        enabled: true
        descriptions: true

  metrics:
    distribution:
      percentiles-histogram:
        all: true
      slo:
        "[http.server.requests]": 50ms, 100ms, 200ms, 500ms, 1s, 2s

  info:
    env:
      enabled: true

  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
          - loggers

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

info:
  app:
    name: "order-service"
    version: "0.0.1"
    description: "Learning..."

url:
  notification-service: ${NOTIFICATION_SERVICE_URL}
  payment-service: ${PAYMENT_SERVICE_URL}

resilience4j:
  retry:
    retryAspectOrder: 2
    configs:
      default:
        maxAttempts: 3
        waitDuration: 200ms
        exponentialBackoffMultiplier: 2.0
        exponentialMaxWaitDuration: 10s
        randomizedWaitFactor: 0.3
        retryExceptions:
          - feign.FeignException
          - org.springframework.web.reactive.function.client.WebClientResponseException
          - project.ivanov.orderservice.order.exception.PaymentFailedException

          - io.netty.handler.timeout.ReadTimeoutException
          - java.util.concurrent.TimeoutException
        #          - java.lang.RuntimeException
        ignoreExceptions:
          - java.lang.IllegalArgumentException
          - io.github.resilience4j.circuitbreaker.CallNotPermittedException
        failAfterMaxAttempts: true
    instances:
      paymentService:
        baseConfig: default
        maxAttempts: 4
  circuitbreaker:
    circuitBreakerAspectOrder: 1
    configs:
      default: # базовая конфигурация для всех экземпляров
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      paymentService:
        baseConfig: default            # наследуем всё из default
        slidingWindowSize: 10          # переопределяем только размер окна
        failureRateThreshold: 40        # и порог ошибок
        minimumNumberOfCalls: 10        # после какого количества начинаем
        recordExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException
          - project.ivanov.orderservice.order.exception.PaymentFailedException
          - io.netty.handler.timeout.ReadTimeoutException
          - java.util.concurrent.TimeoutException
          - io.github.resilience4j.bulkhead.BulkheadFullException
        #          - java.lang.RuntimeException
        ignoreExceptions:
          - java.lang.IllegalArgumentException
  timelimiter:
    instances:
      paymentService:
        timeout-duration: 500ms
        cancel-running-future: true
  bulkhead:
    configs:
      default:
        max-concurrent-calls: 10
        max-wait-duration: 0
        writable-stack-trace-enabled: true
        event-consumer-buffer-size: 100
    instances:
      paymentService:
          base-config: default
          max-concurrent-calls: 5
          max-wait-duration: 0
logging:
  level:
    root: INFO
    project.ivanov.orderservice: DEBUG